### ISSUE TITLE
add fxUSD, fxEUR, fxAUD => forex route

### ISSUE THREAD

**Issue by seahound** [handle-fi/handle-sdk#172]
currently there is an fxUSD to FOREX pool on balancer

https://arbitrum.balancer.fi/#/pool/0x4f14d06cb1661ce1dc2a2f26a10a7cd94393b29c000200000000000000000097

we need to create a pathway for

fxUSD, and other fxTokens => FOREX 

fxUSD => FOREX could go direct via balancer
fxEUR => FOREX, could be;
     fxEUR=>fxUSD (hLP) 
     fxUSD=> FOREX (bal)
     
     
     
    *do we need to consider implications for FOREX=> fxUSD, or FOREX => fxEUR

![image](https://user-images.githubusercontent.com/1622783/182521801-639fa17f-e792-4862-b055-905ad837e0fd.png)

**Comment by Preston-Harrison** [comment]
on hold until handle-routes v1.2.0 is deployed
