### ISSUE TITLE
add routes fxAUD => usdc, USDT

### ISSUE THREAD

**Issue by seahound** [handle-fi/handle-sdk#181]
![image](https://user-images.githubusercontent.com/1622783/182977098-01b21e8d-8912-46f6-a228-5f8a78b1cef1.png)

fxAUD=> fxUSD hLP + fxUSD=> USDC/USDT curve.fi ( could be PSM)

(hLP) + (curve)

**Comment by Preston-Harrison** [comment]
This is pretty much done, just put on hold while waiting for the new contract to be deployed.
