### ISSUE TITLE
check hLP cooldown period - matches GMX

### ISSUE THREAD

**Issue by seahound** [handle-fi/handle-sdk#253]
the cooldown period for a user to withdraw from the hLP needs to be increased? @Preston-Harrison to discuss

https://arbiscan.io/address/0xfc78df3d64e14cf82d2aea52e416d85f8ab148e2#code

1. check what equivalent setting GMX use
2.  check what equivalent setting MYC use

update in gitbook

'global parameters"

**Comment by Preston-Harrison** [comment]
Handle has the same 900 second cooldown as GMX.

**Comment by Preston-Harrison** [comment]
https://app.gitbook.com/o/-MiswpCSPU5ZH4S1SDDG/s/-MbZlpU2Tc6-9k8XDpNZ/~/changes/SWQs1dScZjllsjfU14lw/ here is the gitbook review
