### ISSUE TITLE
Create HandleTokenManager parseNativeToWrapped and deprecate checkForHlpNativeToken

### ISSUE THREAD

**Issue by Preston-Harrison** [handle-fi/handle-sdk#264]
1. Create a new method 'parseNativeToWrapped' which accepts any token and if it is native, parses it to the wrapped native token.

2. Delete checkForHlpNativeToken and replace all instances of it with the new 'parseNativeToWrapped' method

**Comment by rellfy** [comment]
We do not want to delete `checkForHlpNativeToken`, we want to mark it as deprecated. This is to avoid abrupt breaking changes.
